# Site Configuration

baseURL = 'https://www.smollemon.page/'
languageCode = 'vi-VN'
title = 'Smol Lemon'
author = 'Smol Lemon'
copyright = '© 2025 Smol Lemon'
disableHugoGeneratorInject = true
enableRobotsTXT = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false

[taxonomies]
  topics = 'topics'
  tags = 'tags'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[services]
  [services.rss]
    limit = -1

# Markup Configuration

[markup]
  [markup.highlight]
    style = 'catppuccin-latte'
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Paginator

[pagination]
  pagerSize = 25

# Params Configuration

[params]
  favicon = "/images/chiyo_sisyphus.png"
  title = "Smol Lemon"
  description = 'Trang web của Smol Lemon'
  
[params.author]
  name = 'Smol Lemon'

# Menu Configuration

[main]
  [[menu.main]]
  name = "Bài viết"
  url = "/posts/"
  weight = 10

  [[menu.main]]
  name = "Dự án"
  url = "/projects/"
  weight = 20

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 30
  
  [[menu.main]]
  name = "Chủ đề"
  url = "/topics/"
  weight = 40

  [[menu.main]]
  name = "Smol Book"
  url = "https://book.smollemon.page"
  weight = 50

  [[menu.main]]
  name = "Giới thiệu"
  url = "/posts/about/"
  weight = 60

  [[menu.social]]
  name = "Youtube"
  pre = "youtube"
  url = "https://www.youtube.com/@SmolLemon"
  weight = 10

  [[menu.social]]
  name = "Github"
  pre = "github"
  url = "https://www.github.com/SmolLemon"
  weight = 20

  [[menu.social]]
  name = "Codeberg"
  pre = "codeberg"
  url = "https://www.codeberg.org/SmolLemon"
  weight = 30
  
  [[menu.social]]
  name = "Smol Book"
  pre = "smolbook"
  url = "https://book.smollemon.page"
  weight = 40

  [[menu.social]]
  name = "RSS"
  pre = "rss"
  url = "/index.xml"
  weight = 50